---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    service: gateway
spec:
  selector:
    service: gateway
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: menu
  labels:
    service: menu
spec:
  selector:
    service: menu
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    service: orders
spec:
  selector:
    service: orders
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    service: payments
spec:
  selector:
    service: payments
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    service: db
spec:
  selector:
    service: db
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP
  clusterIP: None  # Headless service
